name: Deployment pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches: [main]
        types: [opened, synchronize]

jobs:
    simple_deployment_pipeline:
        runs-on: ubuntu-20.04
        if: ${{ github.event_name == 'push' && !contains(toJSON(github.event.commits.*.message), '#skip') }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'
            - name: Install dependencies
              run: npm install
            - name: Check style
              run: npm run eslint
            - name: Build
              run: npm run build
            - name: Test code
              run: npm run test
            - name: e2e tests
              uses: cypress-io/github-action@v5
              with:
                command: npm run test:e2e
                start: npm run start-prod
                wait-on: http://localhost:5000
            - uses: superfly/flyctl-actions/setup-flyctl@master  
            - name: Deploy app
              if: ${{ github.event_name == 'push' && !contains(toJSON(github.event.commits.*.message), '#skip') }}
              run: flyctl deploy --remote-only
              env:
                FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
            - name: Build failed
              uses: rjstone/discord-webhook-notify@2d99583c5afcbb98ae855619fdfa2f0ec3f371e5
              if: failure()
              with:
                severity: error
                text: Build failed
                description: commit
                details: ${{ github.event.head_commit.url }} by ${{ github.event.head_commit.author.username }} broke the build :(
                webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    tag_release:
        if: ${{ github.event_name == 'push' && !contains(toJSON(github.event.commits.*.message), '#skip') }}
        needs: [simple_deployment_pipeline]
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
            - name: Bump version and push tag
              uses: anothrNick/github-tag-action@8c8163ef62cf9c4677c8e800f36270af27930f42
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                DEFAULT_BUMP: patch
            - name: A new version of Pokedex deployed and tagged
              uses: rjstone/discord-webhook-notify@2d99583c5afcbb98ae855619fdfa2f0ec3f371e5
              if: success()
              with:
                severity: info
                text: A new version of Pokedex deployed
                description: Success!
                details: 'to https://p11-fs-open-pokedex.fly.dev/ by SamuYliK'
                footer: 'Severity: Informational'
                webhookUrl: ${{ secrets.DISCORD_WEBHOOK }} 
