name: Test

on:
    push:
        branches:
            - main
    pull_request:
        branches: [main]
        types: [opened, synchronize]

jobs:
    test_job:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
            - name: test
              run: |
                echo ${payload.head_commit.url}